-- REV 2026-08-12a — migration 18.
-- VERSION CHECK: the first line of the text you paste must read REV
-- 2026-08-12a, and a successful run ends by printing that rev in its
-- completion notice. The Supabase SQL editor keeps the previous paste in a
-- saved snippet, so re-running a tab is not the same as running this file.
-- Migration 18 — category -> tag pre-fill (ADR-002 section 6)
-- GENERATED by scripts/gen_tag_defaults_migration.mjs from wardrobe_taxonomy.js
-- — edit CATEGORY_DEFAULTS in the module and regenerate, never this file.
-- Run once in the Supabase SQL editor on Robes_p0, AFTER migration 17.
-- Re-running is safe: the seed is an upsert, the backfill only touches rows
-- still carrying source 'inferred', and the trigger is create-or-replace.
--
-- WHY THIS IS IN THE DATABASE AND NOT THE CLIENT. The pre-fill has two
-- callers — the one-shot backfill of the existing wardrobe, and every future
-- insert — and implementing it twice guarantees they drift. A trigger is one
-- implementation covering both, and it cannot be bypassed by a client that
-- forgets to apply it. The mapping still lives in wardrobe_taxonomy.js; this
-- file is its compiled form.
--
-- WHAT IT DOES NOT DO. It never overwrites a value she set: both the backfill
-- and the trigger write source 'inferred' only, and skip any row already
-- marked 'user'. Correcting a pre-filled piece is therefore permanent, and
-- the inferred/user split is the correction-rate signal ADR-002 section 6
-- promises.

-- ── preflight ───────────────────────────────────────────────────────────
do $$
begin
  if not exists (select 1 from information_schema.columns
                 where table_schema = 'public' and table_name = 'wardrobe_items'
                   and column_name = 'season_band') then
    raise exception 'ADR-002: migration 17 has not run — apply supabase/season_tags_migration.sql first.';
  end if;
  if to_regclass('public.wardrobe_taxonomy') is null then
    raise exception 'ADR-002: migration 15 has not run — apply supabase/wardrobe_taxonomy_migration.sql first (the pre-fill keys on L2).';
  end if;
end $$;

-- ── the compiled mapping ────────────────────────────────────────────────
-- (sheet_l1, l2) -> the band and wear slugs a newly filed piece starts with.
-- A null l2 row is the fallback for that sheet category, and also covers
-- pieces filed before migration 15, which carry no L2 at all.
create table if not exists public.wardrobe_tag_defaults (
  sheet_l1    text not null,
  l2          text,
  season_band text not null,
  wear_slugs  text[] not null
);

create unique index if not exists idx_tag_defaults_key
  on public.wardrobe_tag_defaults (sheet_l1, coalesce(l2, ''));

alter table public.wardrobe_tag_defaults enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'wardrobe_tag_defaults' and policyname = 'tag_defaults_read'
  ) then
    create policy tag_defaults_read on public.wardrobe_tag_defaults
      for select to authenticated using (true);
  end if;
end $$;

insert into public.wardrobe_tag_defaults (sheet_l1, l2, season_band, wear_slugs) values
  ('Tops', null, 'year_round', array['everyday']::text[]),
  ('Tops', 'T-shirts & tees', 'year_round', array['everyday']::text[]),
  ('Tops', 'Shirts & blouses', 'year_round', array['everyday']::text[]),
  ('Tops', 'Camisoles & sleeveless', 'year_round', array['everyday']::text[]),
  ('Tops', 'Bodysuits', 'year_round', array['everyday']::text[]),
  ('Tops', 'Statement tops', 'year_round', array['everyday']::text[]),
  ('Tops', 'Sweatshirts & hoodies', 'year_round', array['everyday']::text[]),
  ('Knitwear', null, 'autumn_winter', array['everyday']::text[]),
  ('Knitwear', 'Jumpers & sweaters', 'autumn_winter', array['everyday']::text[]),
  ('Knitwear', 'Cardigans', 'autumn_winter', array['everyday']::text[]),
  ('Knitwear', 'Vests & waistcoats', 'autumn_winter', array['everyday']::text[]),
  ('Knitwear', 'Knit separates & sets', 'autumn_winter', array['everyday']::text[]),
  ('Bottoms', null, 'year_round', array['everyday']::text[]),
  ('Bottoms', 'Trousers', 'year_round', array['everyday']::text[]),
  ('Bottoms', 'Jeans', 'year_round', array['everyday']::text[]),
  ('Bottoms', 'Skirts', 'year_round', array['everyday']::text[]),
  ('Bottoms', 'Shorts', 'year_round', array['everyday']::text[]),
  ('Dresses & jumpsuits', null, 'year_round', array['everyday']::text[]),
  ('Dresses & jumpsuits', 'Day dresses', 'year_round', array['everyday']::text[]),
  ('Dresses & jumpsuits', 'Occasion & evening', 'year_round', array['evening', 'occasion']::text[]),
  ('Dresses & jumpsuits', 'Jumpsuits & playsuits', 'year_round', array['everyday']::text[]),
  ('Dresses & jumpsuits', 'Co-ord sets', 'year_round', array['everyday']::text[]),
  ('Outerwear', null, 'autumn_winter', array['everyday']::text[]),
  ('Outerwear', 'Coats', 'autumn_winter', array['everyday']::text[]),
  ('Outerwear', 'Jackets', 'autumn_winter', array['everyday']::text[]),
  ('Outerwear', 'Blazers', 'year_round', array['work', 'everyday']::text[]),
  ('Outerwear', 'Gilets & waistcoats', 'autumn_winter', array['everyday']::text[]),
  ('Tailoring & suiting', null, 'year_round', array['work']::text[]),
  ('Tailoring & suiting', 'Suit separates', 'year_round', array['work']::text[]),
  ('Tailoring & suiting', 'Full suits', 'year_round', array['work']::text[]),
  ('Shoes', null, 'year_round', array['everyday']::text[]),
  ('Shoes', 'Flats', 'year_round', array['everyday']::text[]),
  ('Shoes', 'Heels', 'year_round', array['everyday']::text[]),
  ('Shoes', 'Sandals', 'year_round', array['everyday']::text[]),
  ('Shoes', 'Boots', 'year_round', array['everyday']::text[]),
  ('Shoes', 'Trainers', 'year_round', array['everyday']::text[]),
  ('Bags', null, 'year_round', array['everyday']::text[]),
  ('Bags', 'Everyday bags', 'year_round', array['everyday']::text[]),
  ('Bags', 'Occasion bags', 'year_round', array['everyday']::text[]),
  ('Bags', 'Travel & utility', 'year_round', array['everyday']::text[]),
  ('Bags', 'Small leather goods', 'year_round', array['everyday']::text[]),
  ('Accessories', null, 'year_round', array['everyday']::text[]),
  ('Accessories', 'Belts', 'year_round', array['everyday']::text[]),
  ('Accessories', 'Scarves & wraps', 'year_round', array['everyday']::text[]),
  ('Accessories', 'Hats & headwear', 'year_round', array['everyday']::text[]),
  ('Accessories', 'Eyewear', 'year_round', array['everyday']::text[]),
  ('Accessories', 'Gloves & hosiery', 'year_round', array['everyday']::text[]),
  ('Accessories', 'Other accessories', 'year_round', array['everyday']::text[]),
  ('Jewellery', null, 'year_round', array['everyday']::text[]),
  ('Jewellery', 'Necklaces', 'year_round', array['everyday']::text[]),
  ('Jewellery', 'Earrings', 'year_round', array['everyday']::text[]),
  ('Jewellery', 'Bracelets & rings', 'year_round', array['everyday']::text[]),
  ('Jewellery', 'Watches & pins', 'year_round', array['everyday']::text[]),
  ('Activewear', null, 'year_round', array['active']::text[]),
  ('Activewear', 'Active tops', 'year_round', array['active']::text[]),
  ('Activewear', 'Active bottoms', 'year_round', array['active']::text[]),
  ('Activewear', 'Active layers & sets', 'year_round', array['active']::text[]),
  ('Activewear', 'Sport-specific', 'year_round', array['active']::text[]),
  ('Loungewear & sleepwear', null, 'year_round', array['lounge']::text[]),
  ('Loungewear & sleepwear', 'Loungewear', 'year_round', array['lounge']::text[]),
  ('Loungewear & sleepwear', 'Sleepwear', 'year_round', array['lounge']::text[]),
  ('Loungewear & sleepwear', 'Slippers', 'year_round', array['lounge']::text[]),
  ('Underwear & intimates', null, 'year_round', array['everyday']::text[]),
  ('Underwear & intimates', 'Bras', 'year_round', array['everyday']::text[]),
  ('Underwear & intimates', 'Briefs', 'year_round', array['everyday']::text[]),
  ('Underwear & intimates', 'Shapewear & base layers', 'year_round', array['everyday']::text[]),
  ('Swim & beach', null, 'spring_summer', array['travel']::text[]),
  ('Swim & beach', 'Swimwear', 'spring_summer', array['travel']::text[]),
  ('Swim & beach', 'Cover-ups', 'spring_summer', array['travel']::text[]),
  ('Dresses', null, 'year_round', array['everyday']::text[]),
  ('Swimwear', null, 'spring_summer', array['travel']::text[])
on conflict (sheet_l1, coalesce(l2, '')) do update
  set season_band = excluded.season_band, wear_slugs = excluded.wear_slugs;

-- The seven seed labels, so the trigger can mint a tags row with the right
-- display text. Not pre-created per account — minted on first use.
create table if not exists public.wear_seed_labels (
  slug  text primary key,
  label text not null
);
insert into public.wear_seed_labels (slug, label) values
  ('everyday', 'Everyday'),
  ('work', 'Work'),
  ('evening', 'Evening'),
  ('occasion', 'Occasion'),
  ('travel', 'Travel'),
  ('active', 'Active'),
  ('lounge', 'Lounge')
on conflict (slug) do update set label = excluded.label;

-- ── resolve a piece to its defaults ─────────────────────────────────────
-- Sheet category comes from the L2 when there is one (the L2 name is unique
-- tree-wide, so it recovers its sheet category on its own), else from the
-- legacy `category` column. Mirrors _waSheetCatOf on the client.
create or replace function public.rb_piece_defaults(p_category text, p_l2 text)
returns table (season_band text, wear_slugs text[])
language sql
stable
as $fn$
  with sheet as (
    select coalesce(
      (select t.sheet_l1 from public.wardrobe_taxonomy t where t.l2 = p_l2 limit 1),
      p_category
    ) as sheet_l1
  )
  select d.season_band, d.wear_slugs
  from sheet s
  join public.wardrobe_tag_defaults d
    on d.sheet_l1 = s.sheet_l1
   and coalesce(d.l2, '') = coalesce(
         (select t.l2 from public.wardrobe_taxonomy t where t.l2 = p_l2 limit 1), '')
  limit 1;
$fn$;

-- ── apply them to one piece ─────────────────────────────────────────────
-- SECURITY DEFINER so the writes into tags/tag_pieces cannot trip an RLS
-- check from whatever context the insert arrived in; user_id is taken from
-- the piece row itself, never from auth.uid(), so it cannot cross accounts.
create or replace function public.rb_apply_tag_defaults(p_item_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $fn$
declare
  it     record;
  def    record;
  v_slug text;   -- v_ prefix: a bare `slug` would be ambiguous against the
  v_tid  uuid;   -- slug COLUMN inside the statements below
begin
  select id, user_id, category, category_l2, season_source
    into it from public.wardrobe_items where id = p_item_id;
  if not found then return; end if;

  select * into def from public.rb_piece_defaults(it.category, it.category_l2);
  if not found then return; end if;

  -- The two axes are guarded SEPARATELY. Guarding the whole function on
  -- season_source would mean that picking a season while adding a piece
  -- silently suppressed its wear pre-fill too — two unrelated decisions
  -- coupled by an early return.
  if it.season_source <> 'user' then
    update public.wardrobe_items
       set season_band = def.season_band, season_source = 'inferred'
     where id = it.id;
  end if;

  foreach v_slug in array def.wear_slugs loop
    insert into public.tags (user_id, kind, label, slug, is_seed)
    values (
      it.user_id, 'wear_for',
      coalesce((select l.label from public.wear_seed_labels l where l.slug = v_slug),
               initcap(v_slug)),
      v_slug, true)
    on conflict (user_id, kind, slug) do nothing;

    select t.id into v_tid from public.tags t
     where t.user_id = it.user_id and t.kind = 'wear_for' and t.slug = v_slug;

    if v_tid is not null then
      insert into public.tag_pieces (wardrobe_item_id, tag_id, source)
      values (it.id, v_tid, 'inferred')
      on conflict do nothing;
    end if;
  end loop;
end $fn$;

-- ── future inserts ──────────────────────────────────────────────────────
-- AFTER INSERT rather than BEFORE: the function writes to tags/tag_pieces as
-- well as the piece, and tag_pieces needs the row to exist first.
create or replace function public.rb_tag_defaults_trg()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
begin
  perform public.rb_apply_tag_defaults(new.id);
  return null;
end $fn$;

drop trigger if exists trg_wardrobe_tag_defaults on public.wardrobe_items;
create trigger trg_wardrobe_tag_defaults
  after insert on public.wardrobe_items
  for each row execute function public.rb_tag_defaults_trg();

-- ── one-shot backfill of the existing wardrobe ──────────────────────────
-- Only rows still at source 'inferred'; anything she has corrected is left
-- exactly as it is.
--
-- NOTE the deliberate asymmetry with the trigger. rb_apply_tag_defaults
-- guards the two axes separately, so an INSERT that arrives with a chosen
-- season still gets its wear pre-fill — at insert time there is no prior tag
-- set to respect. The backfill skips a user-touched row ENTIRELY, because
-- there may well be one: adding 'everyday' on top of a piece she has
-- deliberately tagged 'work' alone would be editing her work, not filling a
-- blank. Same function, different caller, different risk.
do $$
declare r record; n bigint := 0;
begin
  for r in select id from public.wardrobe_items where season_source <> 'user' loop
    perform public.rb_apply_tag_defaults(r.id);
    n := n + 1;
  end loop;
  raise notice 'ADR-002 migration 18 complete (rev 2026-08-12a): pre-fill applied to % piece(s).', n;
end $$;

-- ── rollback ────────────────────────────────────────────────────────────
--   drop trigger if exists trg_wardrobe_tag_defaults on public.wardrobe_items;
--   drop function if exists public.rb_tag_defaults_trg();
--   drop function if exists public.rb_apply_tag_defaults(uuid);
--   drop function if exists public.rb_piece_defaults(text, text);
--   drop table if exists public.wardrobe_tag_defaults;
--   drop table if exists public.wear_seed_labels;
--   delete from public.tag_pieces where source = 'inferred';
--   delete from public.tags t where t.is_seed
--     and not exists (select 1 from public.tag_pieces p where p.tag_id = t.id)
--     and not exists (select 1 from public.tag_looks  l where l.tag_id = t.id);
--   update public.wardrobe_items set season_band = 'year_round'
--    where season_source = 'inferred';
