// Regenerates supabase/wardrobe_taxonomy_migration.sql from the taxonomy
// module, so the seed rows and the analyse-prompt tree can never drift.
// Run after any edit to wardrobe_taxonomy.js:
//   node scripts/gen_taxonomy_migration.mjs
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { taxonomyRows } from '../wardrobe_taxonomy.js';

const rows = taxonomyRows();
const q = v => "'" + String(v).replace(/'/g, "''") + "'";
const values = rows.map(r => `  (${q(r.l1)}, ${q(r.sheet_l1)}, ${q(r.l2)}, ${q(r.l3)})`).join(',\n');

const sql = `-- Migration 15 — 3-level wardrobe taxonomy (2026-07-31)
-- GENERATED by scripts/gen_taxonomy_migration.mjs from wardrobe_taxonomy.js
-- (the taxonomy sheet's 350 item types) — edit the module and regenerate,
-- never this file. Run once in the Supabase SQL editor on Robes_p0;
-- re-running is safe (adds/upgrades are idempotent upserts).
--
-- \`category\` stays the back-compat single-level L1 every existing surface
-- reads; category_l2/category_l3 are nullable — null is the NORMAL state for
-- every pre-migration piece, no backfill required or wanted.

alter table public.wardrobe_items
  add column if not exists category_l2 text,
  add column if not exists category_l3 text;

-- Lookup table: the valid (l2, l3) nodes plus the legacy category (l1) and
-- the sheet's own top-level category (sheet_l1) each node belongs to. Keeps
-- key drift from the analyse prompt out of the data (mirrors how
-- planned_days check-caps slot).
create table if not exists public.wardrobe_taxonomy (
  l1       text not null,
  sheet_l1 text not null,
  l2       text not null,
  l3       text not null,
  primary key (l2, l3)
);

alter table public.wardrobe_taxonomy enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'wardrobe_taxonomy' and policyname = 'taxonomy_read'
  ) then
    create policy taxonomy_read on public.wardrobe_taxonomy
      for select to authenticated using (true);
  end if;
end $$;

insert into public.wardrobe_taxonomy (l1, sheet_l1, l2, l3) values
${values}
on conflict (l2, l3) do update set l1 = excluded.l1, sheet_l1 = excluded.sheet_l1;

-- Composite FK: when BOTH columns are set the pair must be a real taxonomy
-- node (MATCH SIMPLE — a row with l3 null passes, so "l2 known, l3 unsure"
-- stays writable). The server validates before writing; this is the backstop.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'wardrobe_items_taxonomy_fkey'
  ) then
    alter table public.wardrobe_items
      add constraint wardrobe_items_taxonomy_fkey
      foreign key (category_l2, category_l3)
      references public.wardrobe_taxonomy (l2, l3);
  end if;
end $$;

-- The Refine drawer's Type filter is the first surface reading category_l2.
create index if not exists idx_wardrobe_items_category_l2
  on public.wardrobe_items (category_l2) where category_l2 is not null;
`;

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'wardrobe_taxonomy_migration.sql');
writeFileSync(out, sql);
console.log(`wrote ${out} (${rows.length} seed rows)`);
